name: Latest Blog Posts
on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://YOUR_BLOG_URL/feed.xml"
          max_post_count: 5
